package server

import (
	"os"
	"path/filepath"
	"testing"
)

func TestNormalise(t *testing.T) {
	ok := map[string]string{
		"forge":           "forge",
		"forge.mpd.test":  "forge",
		"  Forge ":        "forge",
		"WARP.MPD.TEST":   "warp",
		"runner-1":        "runner-1",
		"devoci.mpd.test": "devoci",
	}
	for in, want := range ok {
		got, err := Normalise(in)
		if err != nil {
			t.Errorf("Normalise(%q) errored: %v", in, err)
			continue
		}
		if got != want {
			t.Errorf("Normalise(%q) = %q, want %q", in, got, want)
		}
	}

	bad := []string{
		"",                  // empty
		"126",               // VM zone (3-digit)
		"099",               // VM zone even though not a managed id
		"bad_name",          // charset (underscore)
		"-lead",             // leading hyphen
		"trail-",            // trailing hyphen
		"forge.example.com", // outside mpd.test
		"a.b.mpd.test",      // more than one label under mpd.test
	}
	for _, in := range bad {
		if got, err := Normalise(in); err == nil {
			t.Errorf("Normalise(%q) = %q, want error", in, got)
		}
	}
}

func TestValidateIP(t *testing.T) {
	for _, ip := range []string{"10.1.10.100", "10.0.0.1", "::1", "fe80::1"} {
		if err := ValidateIP(ip); err != nil {
			t.Errorf("ValidateIP(%q) rejected a valid address: %v", ip, err)
		}
	}
	for _, ip := range []string{"forge", "1.2.3", "999.1.1.1", "10.0.0.0/24", ""} {
		if err := ValidateIP(ip); err == nil {
			t.Errorf("ValidateIP(%q) accepted an invalid address", ip)
		}
	}
}

func TestIsVMZoneLabel(t *testing.T) {
	for _, l := range []string{"126", "001", "099", "254"} {
		if !isVMZoneLabel(l) {
			t.Errorf("isVMZoneLabel(%q) = false, want true", l)
		}
	}
	for _, l := range []string{"forge", "12", "1234", "12a", ""} {
		if isVMZoneLabel(l) {
			t.Errorf("isVMZoneLabel(%q) = true, want false", l)
		}
	}
}

func TestServiceHostAndEntry(t *testing.T) {
	if got := ServiceHost("forge"); got != "forge.mpd.test" {
		t.Errorf("ServiceHost = %q", got)
	}
	if got := (Entry{Name: "warp", IP: "1.2.3.4"}).Host(); got != "warp.mpd.test" {
		t.Errorf("Entry.Host = %q", got)
	}
}

// TestSaveLoadRoundTrip also proves that an unknown key on disk (like the
// legacy MPD_SERVER_KIND) does not break Load.
func TestSaveLoadRoundTrip(t *testing.T) {
	root := t.TempDir()
	t.Setenv("MPD_VIRT_TEST_ROOT", root)

	e := Entry{Name: "forge", IP: "10.1.10.100"}
	if err := Save(e); err != nil {
		t.Fatalf("Save: %v", err)
	}
	// Append a stray annotation key, as a real registry had.
	f, err := os.OpenFile(EnvFile("forge"), os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	f.WriteString("MPD_SERVER_KIND=forgejo\n")
	f.Close()

	got, err := Load("forge")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got != e {
		t.Errorf("round trip = %+v, want %+v", got, e)
	}

	all, err := LoadAll()
	if err != nil || len(all) != 1 || all[0] != e {
		t.Errorf("LoadAll = %+v, err %v", all, err)
	}
	if !Exists("forge") {
		t.Error("Exists(forge) = false")
	}
}

func TestWriteHostsFile(t *testing.T) {
	root := t.TempDir()
	t.Setenv("MPD_VIRT_TEST_ROOT", root)
	if err := Save(Entry{Name: "warp", IP: "10.1.10.102"}); err != nil {
		t.Fatal(err)
	}
	if err := Save(Entry{Name: "forge", IP: "10.1.10.100"}); err != nil {
		t.Fatal(err)
	}
	path, err := WriteHostsFile()
	if err != nil {
		t.Fatalf("WriteHostsFile: %v", err)
	}
	if path != filepath.Join(root, "conf", "lan-hosts") {
		t.Errorf("path = %q", path)
	}
	body, _ := os.ReadFile(path)
	// Entries are sorted by name: forge before warp.
	want := "# mpd-virt LAN service records.\n" +
		"# Generated by `mpd-virt server`; edits are overwritten.\n" +
		"10.1.10.100\tforge.mpd.test\n" +
		"10.1.10.102\twarp.mpd.test\n"
	if string(body) != want {
		t.Errorf("hosts body =\n%q\nwant\n%q", body, want)
	}
}

func TestRemove(t *testing.T) {
	root := t.TempDir()
	t.Setenv("MPD_VIRT_TEST_ROOT", root)
	if err := Save(Entry{Name: "forge", IP: "1.2.3.4"}); err != nil {
		t.Fatal(err)
	}
	if err := Remove("forge"); err != nil {
		t.Fatalf("Remove: %v", err)
	}
	if Exists("forge") {
		t.Error("still exists after Remove")
	}
	// Removing an absent server is a no-op, not an error.
	if err := Remove("nope"); err != nil {
		t.Errorf("Remove(absent) = %v", err)
	}
}
